name: CI/CD

on:
    push:
        branches: [main]

jobs:
    continuous_integration:
        name: Continuous integration
        runs-on: ubuntu-latest

        steps:
            - name: Checking out code
              uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Installing dependencies
              run: yarn install

            - name: Testing project
              run: yarn test

            - name: Project coverage
              run: npx codecov -f ./coverage/coverage-final.json

            - name: Building project
              run: yarn build
