name: CI/CD package publish

on:
    release:
        types: published

jobs:
    continuous_integration:
        name: Continuous integration package publish
        runs-on: ubuntu-latest

        steps:
            - name: Checking out code
              uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: 'https://www.npmjs.com'
                  scope: '@clorofila'

            - name: Installing dependencies
              run: yarn install

            - name: Testing project
              run: yarn test

            - name: Building project
              run: yarn build

            - name: Publish package
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
