name: CI/CD Publish release

on:
  release:
    types: published
    
jobs:
  publish_release:
    name: Package publish
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          scope: '@clorofila'
      - name: Installing dependencies
        run: yarn install
      - name: Testing project
        run: yarn test
      - name: Building project
        run: yarn build
      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
